name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/test/simple_transport_test/bin -S ${{github.workspace}}/test/simple_transport_test -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/test/simple_transport_test/bin --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/test/simple_transport_test/bin
      run: ./simple_transport_test

